/**
 * Wording of the admin area. English only, and deliberately outside the learner-facing screen
 * texts (shared/lib/i18n) so admins are not asked to translate their own tools.
 */
export const adminText = {
  title: 'Kuhedu Admin',
  openApp: 'Open app',
  signOut: 'Sign out',
  sectionsLabel: 'Admin sections',
  localNotice:
    'No database yet: changes are saved in this browser only and show up in other tabs of the same browser.',

  nav: {
    texts: 'Screen texts',
    curriculum: 'Curriculum',
    lessons: 'Lessons',
    landing: 'Landing page',
    languages: 'Languages',
    profiles: 'Profile pictures',
  },

  actions: {
    save: 'Save changes',
    saveShort: 'Save',
    discard: 'Discard',
    resetAll: 'Reset to defaults',
    resetAllShort: 'Reset',
    resetAllConfirm:
      'Reset this section to the built-in defaults? Your saved changes will be lost.',
    saved: 'Saved. Open tabs of the app update straight away.',
    reset: 'Reset to the built-in defaults.',
    unsaved: 'You have unsaved changes.',
    storageFull:
      'Could not save: this browser’s storage is full. Remove or replace some uploaded images and try again.',
  },

  image: {
    upload: 'Upload image',
    replace: 'Replace image',
    useDefault: 'Use default',
    remove: 'Remove image',
    processing: 'Preparing image…',
    failed: 'That file could not be read as an image. Try a PNG, JPEG or WebP file.',
    tooLarge: 'That image is too large even after shrinking. Try a smaller one.',
    none: 'No image',
  },

  /** Shared by the editors of per-language wording (Screen texts, Curriculum). */
  wording: {
    languageLegend: 'Language to edit',
    statusBuiltIn: 'Built-in',
    statusEdited: 'Edited',
    statusMissing: 'Missing — shows English',
    resetOne: 'Reset this text',
  },

  texts: {
    heading: 'Screen texts',
    intro:
      'Every text learners see, in each language. Edit a text to replace the built-in one for that language; pick a screen to see only its texts.',
    screenFilter: 'Screen',
    allScreens: 'All screens',
    search: 'Search texts',
    searchPlaceholder: 'Search by text or key',
    noMatches: 'No texts match your search.',
    /** Extra guidance for a group, shown under its title. */
    groupNotes: {
      signIn:
        '“{brand}” in the title is replaced by the brand name. The brand name, tagline and logo shown on this screen are edited under Landing page.',
    },
    groups: {
      signIn: 'Sign in and sign up',
      language: 'Onboarding · Choose language',
      profile: 'Onboarding · About you',
      placement: 'Onboarding · Placement test',
      onboarding: 'Onboarding · Shared',
      main: 'Home, journey and the other main screens',
      profileScreen: 'Profile and themes',
      app: 'App name and navigation',
      errors: 'Errors',
      other: 'Other',
    },
  },

  curriculum: {
    heading: 'Curriculum',
    intro:
      'The 50-week course learners see on Home, in each language: ten sections of five weeks. Each week has a goal (an “I can …” statement), the real-life situation it is set in, the challenge the learner has to manage there, and an overview screen with a picture and five outcomes.',
    sectionPicker: 'Section',
    section: 'Section',
    weeks: 'Weeks',
    week: 'Week',
    sectionName: 'Section name',
    goal: 'Goal',
    situation: 'Situation',
    challenge: 'Challenge',
    overview: 'Weekly overview',
    overviewNote:
      'Shown when a learner opens the week: the situation above, this picture, and five things they will be able to do. The fifth sums the week up.',
    picture: 'Picture',
    pictureHint:
      'Landscape image, ideally 640 × 360. The same in every language. Without one, a drawing is shown.',
    outcome: 'Outcome',
    english: 'English',
    missing: 'missing',
    previous: 'Previous section',
    next: 'Next section',
  },

  lessons: {
    heading: 'Lessons',
    intro:
      'Each day of a week is one screen, the same for every week; here you fill it with a week’s content. Day 1 is a short conversation to watch and listen to; Day 2 is the week’s words to hear and say; Day 3 is sentences to translate into English and say; Day 4 is a role-play with a partner whose lines you write; Day 5 is the week’s challenge, done in one recording; Day 6 is an optional review of the week; Day 7 is an optional real-world challenge, the week’s conversation in other places. A day without content tells learners that its lessons are coming soon.',
    weekPicker: 'Week',
    week: 'Week',
    day: 'Day',
    dayLegend: 'Day to fill',
    dayWatch: 'Day 1 · Watch and listen',
    dayWords: 'Day 2 · Learn useful words',
    dayTranslate: 'Day 3 · Translate and speak',
    dayTalk: 'Day 4 · Role-play',
    dayPerform: 'Day 5 · Challenge',
    dayReview: 'Day 6 · Review',
    dayExtend: 'Day 7 · Real-world challenge',
    lines: 'lines',
    noConversation: 'no conversation yet',
    translationLegend: 'Translation to write',
    conversation: 'Conversation',
    conversationIntro:
      'In the order it is said. Keep each line to a sentence or two, in words the week teaches.',
    situation: 'This week’s situation',
    empty: 'This week has no conversation yet. Add a line to start one.',
    line: 'Line',
    speaker: 'Speaker',
    english: 'English',
    addLine: 'Add line',
    moveUp: 'Move up: line',
    moveDown: 'Move down: line',
    remove: 'Remove line',
    useBuiltIn: 'Use built-in',
    removeContent: 'Remove',
    video: 'Video',
    videoIntro:
      'Optional. Without a video, the phone’s own voice reads the conversation over the week’s picture (uploaded under Curriculum). Learners must hear or watch it through once before they can go on.',
    videoUrl: 'Video link',
    videoHint:
      'A link to a video file kept elsewhere, for example an .mp4. A video cannot be uploaded here: there is no server yet.',
    errorSpeaker: 'Enter who says this.',
    errorText: 'Enter what they say.',
    errorVideo: 'Use a link that starts with https://',
    errorNoLines: 'Add the conversation the video shows: at least one line.',
    errorTooMany: 'That is the maximum number of lines.',
    errorElsewhere: 'Finish or remove what is unfinished in:',

    wordCount: 'words',
    noWords: 'no words yet',
    words: 'Words',
    wordsIntro:
      'The words learners tap to hear and then say, in the order shown. Up to 8; four to six fit a phone best. The phone’s own voice says each word as it is written.',
    emptyWords: 'This week has no words yet. Add a word to start.',
    word: 'Word',
    wordField: 'Word or phrase',
    phonetic: 'Phonetic spelling',
    phoneticHint: 'Optional, for example /ˈkɒfi/.',
    meaning: 'Meaning',
    wordPicture: 'Picture',
    wordPictureHint:
      'Square image, ideally 320 × 320. Without one, the word’s first letter is shown.',
    addWord: 'Add word',
    moveWordUp: 'Move up: word',
    moveWordDown: 'Move down: word',
    removeWord: 'Remove word',
    errorWord: 'Enter the word.',
    errorDuplicateWord: 'This word is already in the list.',
    errorTooManyWords: 'That is the maximum number of words.',

    sentenceCount: 'sentences',
    noSentences: 'no sentences yet',
    sentences: 'Sentences',
    sentencesIntro:
      'Learners get these one at a time: they read the sentence in their own language, write it in English, then say it. Up to 6. A typed translation gets a tick when it says the same as the answer or one of the other accepted sentences; capitals, punctuation and short forms (I’m / I am) do not matter. Anything else is shown beside the answer, never marked wrong. A learner whose language a sentence is not written in gets the English to listen to and say.',
    emptySentences: 'This week has no sentences yet. Add a sentence to start.',
    sentence: 'Sentence',
    sentenceEnglish: 'English: the answer',
    alsoAccepted: 'Also accepted',
    alsoAcceptedHint:
      'Optional. Other English sentences that are just as right, one per line, up to 4.',
    sentenceIn: 'Sentence in',
    tips: 'Tips',
    tipsHint: 'Optional. One tip per line, up to 3.',
    tipsEnglishHint:
      'Optional. One tip per line, up to 3. Shown to learners whose language has no tips of its own.',
    addSentence: 'Add sentence',
    moveSentenceUp: 'Move up: sentence',
    moveSentenceDown: 'Move down: sentence',
    removeSentence: 'Remove sentence',
    errorSentence: 'Enter the sentence in English.',
    errorTooManySentences: 'That is the maximum number of sentences.',

    turnCount: 'turns',
    noRoleplay: 'no role-play yet',
    partner: 'Partner',
    partnerIntro:
      'Who the learner talks to. There is no AI yet: the partner says the lines written below, in order, whatever the learner answers, and the screen does not call it AI.',
    partnerName: 'Name or role',
    partnerNameHint: 'As it reads after “Talk to”, for example: Ravi, or: the barista.',
    partnerPicture: 'Picture of the partner',
    partnerPictureHint:
      'Square image, ideally 320 × 320; shown in a circle. Without one, a drawn figure is shown.',
    turns: 'Turns',
    turnsIntro:
      'One turn is a line of the partner and the learner’s answer to it. Up to 8. The phone’s own voice says the partner’s lines. What the learner says is recorded for them to hear, not recognised or rated; they can also skip a turn. The suggested reply is the last hint, and is shown once the turn is over.',
    emptyTurns: 'This week has no role-play yet. Add a turn to start one.',
    turn: 'Turn',
    partnerLine: 'Partner says',
    reply: 'Suggested reply',
    cue: 'What to say, in',
    cueHint:
      'The first hint: what the learner should say, without the English words. For example: Tell him your name.',
    addTurn: 'Add turn',
    moveTurnUp: 'Move up: turn',
    moveTurnDown: 'Move down: turn',
    removeTurn: 'Remove turn',
    errorPartnerName: 'Enter who the learner talks to.',
    errorPartnerLine: 'Enter what the partner says.',
    errorReply: 'Enter a reply the learner could give.',
    errorNoTurns: 'Add what is said: at least one turn.',
    errorTooManyTurns: 'That is the maximum number of turns.',

    taskCount: 'tasks',
    noChallenge: 'no challenge yet',
    challenge: 'Challenge',
    challengeIntro:
      'The week’s task done from start to finish: the learner reads what to do, records themselves doing all of it in one go (up to 2 minutes), then listens back and ticks what they managed. Nothing is sent or assessed yet, and the screen says so. The picture is the week’s own, uploaded under Curriculum. Learners read the name, the instruction and the tasks in their own language, or in English where it is not written in theirs.',
    challengeTitle: 'Name of the challenge',
    challengeTitleIn: 'Name in',
    instruction: 'Instruction',
    instructionIn: 'Instruction in',
    instructionHint: 'Optional. A sentence shown under the name.',
    tasks: 'Tasks',
    tasksIntro:
      'What the learner should do, in the order to do it. Up to 6, each short enough for one line of a phone.',
    emptyTasks: 'This week has no challenge yet. Add a task to start one.',
    task: 'Task',
    taskText: 'What to do',
    taskIn: 'In',
    addTask: 'Add task',
    moveTaskUp: 'Move up: task',
    moveTaskDown: 'Move down: task',
    removeTask: 'Remove task',
    phrases: 'Useful phrases',
    phrasesIntro:
      'Help for a learner who is stuck. It stays out of sight until they tap “I need help”, and using it changes nothing else.',
    phrasesField: 'Phrases',
    phrasesHint:
      'Optional. English, one per line, up to 6. The phone’s own voice can say each one.',
    errorChallengeTitle: 'Enter the name of the challenge.',
    errorTask: 'Enter what to do.',
    errorNoTasks: 'Add what to do: at least one task.',
    errorTooManyTasks: 'That is the maximum number of tasks.',

    reviewPartCount: 'of 3 review parts',
    noReview: 'no review yet',
    review: 'Weekly review',
    reviewIntro:
      'An optional day: a list of up to five things to practise, each ticked once it is done. One of them is enough to finish the day, and the day can be skipped. Three are written here: the quick quiz, a second conversation to listen to, and a second, shorter role-play. The other two repeat the week and are not written again: “Speaking practice” is Day 5’s challenge, and “Vocabulary flashcards” are Day 2’s words. A part with nothing in it is left off the learner’s list; a week with nothing in any of the five says the day is coming soon.',
    reviewPartLegend: 'Part to fill',
    reviewQuiz: 'Quick quiz',
    reviewListening: 'Listening practice',
    reviewRoleplay: 'Mini role-play',
    quiz: 'Questions',
    quizIntro:
      'Asked one at a time, up to 8. The learner picks one of the English choices and checks it: a right answer gets a tick; a wrong one is shown the answer, and the question comes back once after the others. Learners read the question in their own language, or in English where it is not written in theirs. The choices are English, and the right answer’s place among them changes from question to question.',
    emptyQuiz: 'This week has no quiz yet. Add a question to start one.',
    question: 'Question',
    questionText: 'What is asked',
    questionIn: 'In',
    quizAnswer: 'Right answer',
    quizAnswerHint: 'English, as the phone’s own voice will say it.',
    quizOthers: 'Other choices',
    quizOthersHint: 'English, one per line, 1 to 3. None may say the same as the right answer.',
    addQuestion: 'Add question',
    moveQuestionUp: 'Move up: question',
    moveQuestionDown: 'Move down: question',
    removeQuestion: 'Remove question',
    errorQuestion: 'Enter what is asked.',
    errorQuizAnswer: 'Enter the right answer.',
    errorQuizOthers: 'Enter at least one other choice.',
    errorQuizSameChoice: 'A choice is the same as the right answer, or is listed twice.',
    errorTooManyQuestions: 'That is the maximum number of questions.',

    scenarioCount: 'scenarios',
    noScenarios: 'no scenarios yet',
    scenarios: 'Scenarios',
    scenariosIntro:
      'An optional day, the last of the week: the week’s conversation in other places. The learner picks a scenario and a level, then takes it as a role-play like Day 4’s — there is no AI yet, so the partner says the lines written here, in order. Up to 3 scenarios. The three levels are not written: they are amounts of help with the same lines. “Easier” shows what to say on every turn, “Standard” only when the learner asks, “Harder” not at all. One scenario taken to its end is enough to finish the day, and the day can be skipped. The picture above the choices is the week’s own, uploaded under Curriculum.',
    emptyScenarios: 'This week has no scenarios yet. Add a scenario to start.',
    scenarioLegend: 'Scenario to fill',
    scenario: 'Scenario',
    scenarioName: 'Name of the scenario',
    scenarioNameIn: 'Name in',
    scenarioNameHint: 'Short, as it reads on its button, for example: Takeaway café.',
    addScenario: 'Add scenario',
    moveScenarioUp: 'Move earlier: scenario',
    moveScenarioDown: 'Move later: scenario',
    removeScenario: 'Remove scenario',
    errorScenarioName: 'Enter the name of the scenario.',
    errorTooManyScenarios: 'That is the maximum number of scenarios.',
  },

  landing: {
    heading: 'Landing page',
    intro: 'The first screen visitors see, before they choose a language.',
    brand: 'Brand',
    logo: 'Logo',
    logoHint: 'Square image, at least 128 × 128.',
    brandName: 'Brand name',
    tagline: 'Tagline',
    hero: 'Hero image',
    heroImage: 'Hero image',
    heroHint: 'Portrait image, ideally 1080 × 1920. Without one, a themed illustration is shown.',
    heroAlt: 'Image description',
    heroAltHint: 'Read aloud by screen readers. Leave empty if the image is only decoration.',
    focalPoint: 'Keep visible when cropped',
    focalTop: 'Top of the image',
    focalCenter: 'Centre of the image',
    focalBottom: 'Bottom of the image',
    overlay: 'Text over the image',
    overlayIntro:
      'Write the headline once per language. The landing page shows them one at a time, sliding to the next every 5 seconds, in this order.',
    headline: 'Headline',
    headlineLang: 'Language of headline',
    subheadline: 'Sub-headline',
    optional: '(optional)',
    addHeadline: 'Add headline',
    moveHeadlineUp: 'Move up: headline',
    moveHeadlineDown: 'Move down: headline',
    removeHeadline: 'Remove headline',
    errorHeadline: 'Enter the headline text.',
    buttons: 'Buttons',
    primaryLabel: 'Main button',
    signInPrompt: 'Text before the sign-in link',
    signInLabel: 'Sign-in link',
  },

  languages: {
    heading: 'Languages',
    intro:
      'The mother tongues learners can choose. The app is shown in the chosen language; add its texts under Screen texts.',
    add: 'Add language',
    language: 'Language',
    flag: 'Flag',
    flagHint: 'Square image; shown in a circle.',
    code: 'Language code',
    codeHint: 'For example bn, hi, ta, en.',
    nativeName: 'Name in its own script',
    caption: 'Note in brackets (optional)',
    captionHint: 'Usually the English name.',
    moveUp: 'Move up',
    moveDown: 'Move down',
    remove: 'Remove language',
    defaultLanguage: 'Pre-selected language',
    defaultHint: 'Suggested when nothing is known about the learner.',
    errorCode: 'Use a short code such as bn or en-IN.',
    errorDuplicate: 'This code is already used by another language.',
    errorName: 'Enter the language name.',
    errorEmpty: 'Keep at least one language.',
    errorTooMany: 'That is the maximum number of languages.',
  },

  profiles: {
    heading: 'Profile pictures',
    intro:
      'Shown on “Tell us about yourself”. Each age group flips between its male and female picture.',
    male: 'Male picture',
    female: 'Female picture',
    hint: 'Square image; shown in a circle.',
    groups: { child: 'Child (6–12)', teen: 'Teenager (13–18)', adult: 'Adult (18+)' },
  },
} as const
