import type { WeekOutcomes } from '../curriculum'

/**
 * What a learner will be able to do by the end of each week, Week 1 first: four steps and, last,
 * the week's whole challenge. Shown on the weekly overview.
 * Written by the assistant from the week's goal, situation and challenge; Week 20 is the design's
 * own wording. Kept apart from `en.ts` so the three-line map of the course stays readable there.
 * TODO(content): expert review.
 */
export const enOutcomes: readonly WeekOutcomes[] = [
  // Section 1
  [
    'Greet someone politely',
    'Say your name',
    'Ask someone their name',
    'Respond to a greeting',
    'Complete a short first meeting',
  ],
  [
    'Ask where someone is from',
    'Say where you live',
    'Talk about your work or study',
    'Answer simple questions about yourself',
    'Get to know a new person in a short chat',
  ],
  [
    'Name your family members',
    'Say how each person is related to you',
    'Describe a family member',
    'Ask about someone’s family',
    'Introduce your family to someone',
  ],
  [
    'Say what you like',
    'Say what you don’t like',
    'Ask about someone’s likes and dislikes',
    'Give a simple reason for a preference',
    'Find something you have in common',
  ],
  [
    'Give a short introduction about yourself',
    'Add details about your family and interests',
    'Answer follow-up questions',
    'Ask a question in return',
    'Introduce yourself confidently at an event',
  ],
  // Section 2
  [
    'Describe how someone looks',
    'Describe someone’s personality',
    'Say what someone is wearing',
    'Ask questions to identify a person',
    'Describe someone so a friend can recognise them',
  ],
  [
    'Describe an object’s colour, size and shape',
    'Say where something is',
    'Say who something belongs to',
    'Ask about a lost object',
    'Help someone find a missing object',
  ],
  [
    'Name the rooms and places around you',
    'Describe your home',
    'Explain where things are',
    'Talk about your neighbourhood',
    'Show someone around your home or area',
  ],
  [
    'Say what you do every day',
    'Say when you do things',
    'Say how often you do something',
    'Ask about someone’s routine',
    'Share a typical day with a friend',
  ],
  [
    'Say what you are doing now',
    'Describe what people are doing in a picture',
    'Ask what someone is doing',
    'Describe what is around you on a call',
    'Explain a scene on a video call',
  ],
  // Section 3
  [
    'Name everyday foods and drinks',
    'Say what you like to eat',
    'Describe how food tastes',
    'Ask what someone would like',
    'Choose a meal together',
  ],
  [
    'Say how you feel',
    'Give a reason for a feeling',
    'Ask how someone is feeling',
    'Respond kindly to someone’s feelings',
    'Talk about how your day went',
  ],
  [
    'Compare two things',
    'Say which one you prefer',
    'Explain why you prefer it',
    'Ask for someone’s opinion on a choice',
    'Choose between two options together',
  ],
  [
    'Say what you can do',
    'Say what you cannot do',
    'Ask what someone can do',
    'Ask for permission',
    'Plan an activity around what everyone can do',
  ],
  [
    'Describe the steps of a simple task',
    'Use words like first, next and then',
    'Give a reason',
    'Give an example',
    'Explain how you do something familiar',
  ],
  // Section 4
  [
    'Start a conversation with small talk',
    'Show interest in what someone says',
    'Introduce one person to another',
    'Join a conversation politely',
    'Mix with people at a gathering',
  ],
  [
    'Ask for help politely',
    'Ask for directions',
    'Understand simple directions',
    'Ask someone to repeat or explain',
    'Find your way in an unfamiliar place',
  ],
  [
    'Suggest an idea',
    'Make a polite request',
    'Accept a suggestion',
    'Decline politely',
    'Make a plan with a friend or colleague',
  ],
  [
    'Say that you agree',
    'Disagree politely',
    'Give a different opinion',
    'Explain your reason',
    'Decide together what to do',
  ],
  [
    'Order food and drink',
    'Ask about the menu and price',
    'Make special requests',
    'Respond to a follow-up question',
    'Complete a natural café conversation',
  ],
  // Section 5
  [
    'Ask open questions',
    'Ask follow-up questions',
    'Ask for more detail',
    'React to an answer',
    'Interview someone about their interests',
  ],
  [
    'Understand the main message',
    'Show that you are listening',
    'Respond to good and bad news',
    'Ask about what you heard',
    'Catch up with a friend naturally',
  ],
  [
    'Add details to your answers',
    'Ask related questions',
    'Move on to a new topic',
    'Avoid ending a conversation too soon',
    'Keep a conversation going for a few minutes',
  ],
  [
    'Say that you did not understand',
    'Ask someone to repeat',
    'Ask someone to explain in another way',
    'Check that you understood correctly',
    'Sort out a misunderstanding on the phone',
  ],
  [
    'Greet someone you did not expect to meet',
    'Answer unexpected questions',
    'Take time to think while speaking',
    'Ask questions of your own',
    'Hold a conversation without a script',
  ],
  // Section 6
  [
    'Say what you did yesterday',
    'Say when things happened',
    'Tell events in order',
    'Ask someone about their day',
    'Share what happened yesterday',
  ],
  [
    'Say when and where something happened',
    'Tell what happened',
    'Describe how you felt',
    'Explain why it mattered',
    'Tell someone about a special day',
  ],
  [
    'Say what you are going to do',
    'Talk about arrangements you have made',
    'Make a prediction',
    'Ask about someone’s plans',
    'Discuss plans for a weekend or holiday',
  ],
  [
    'Say what has changed recently',
    'Compare your life before and now',
    'Say how long something has been true',
    'Ask what is new with someone',
    'Catch up with someone after a long time',
  ],
  [
    'Suggest different options',
    'Talk about advantages and disadvantages',
    'Give advice',
    'Agree on a plan',
    'Plan a trip or activity as a group',
  ],
  // Section 7
  [
    'State your opinion clearly',
    'Support it with reasons',
    'Give an example',
    'Ask what others think',
    'Discuss a topic you care about',
  ],
  [
    'Show sympathy',
    'Ask thoughtful questions',
    'Offer encouragement',
    'Respond sensitively to bad news',
    'Support a friend after a difficult day',
  ],
  [
    'Acknowledge another point of view',
    'Disagree without being rude',
    'Support your position',
    'Find points you agree on',
    'Take part in a friendly debate',
  ],
  [
    'Explain a problem clearly',
    'Suggest possible causes',
    'Propose solutions',
    'Compare solutions',
    'Solve a practical problem with someone',
  ],
  [
    'Explain the benefits of an idea',
    'Respond to objections',
    'Offer a compromise',
    'Check whether someone is convinced',
    'Persuade a friend or team to try your idea',
  ],
  // Section 8
  [
    'Describe size, shape, colour and material',
    'Describe a place using the senses',
    'Compare it with something familiar',
    'Add details in a clear order',
    'Help someone picture a place or object',
  ],
  [
    'Set the scene',
    'Tell events in order',
    'Build up to the surprising part',
    'Describe how people reacted',
    'Tell a story that keeps a listener interested',
  ],
  [
    'List what is needed',
    'Give steps in a logical order',
    'Warn about common mistakes',
    'Check that the other person understands',
    'Teach someone a task from start to finish',
  ],
  [
    'Open a short talk',
    'Link ideas with words like because, so and however',
    'Show how one idea leads to another',
    'Finish with a clear conclusion',
    'Give a short, well-organised talk',
  ],
  [
    'Pick out the main points',
    'Leave out unimportant details',
    'Explain in simpler words',
    'Connect the points',
    'Summarise a video, article or conversation',
  ],
  // Section 9
  [
    'Ask for travel information',
    'Understand announcements and instructions',
    'Check in at a hotel or a counter',
    'Explain a travel problem',
    'Manage a journey from start to finish',
  ],
  [
    'Ask a question in class',
    'Explain your answer',
    'Ask for clarification',
    'Add to what someone else said',
    'Take part in a group discussion',
  ],
  [
    'Describe your role and responsibilities',
    'Give a short update',
    'Ask questions in a meeting',
    'Discuss next steps',
    'Take part in a project discussion',
  ],
  [
    'Start and end a phone call politely',
    'Leave a clear voice message',
    'Speak clearly without visual cues',
    'Deal with a bad connection',
    'Take part in a video meeting',
  ],
  [
    'Explain what happened',
    'Ask for help urgently',
    'Make a polite complaint',
    'Negotiate a solution',
    'Handle an unexpected problem calmly',
  ],
  // Section 10
  [
    'Give precise details',
    'Use time references correctly',
    'Check that you were understood',
    'Correct a misunderstanding',
    'Explain information accurately when details matter',
  ],
  [
    'Describe a word you cannot remember',
    'Use a different word with a similar meaning',
    'Say something again in another way',
    'Explain an unfamiliar idea',
    'Keep talking when the exact word is missing',
  ],
  [
    'Speak in connected groups of words',
    'Stress the important words',
    'Pause in natural places',
    'Reduce unnecessary hesitation',
    'Hold a five-minute conversation with a new person',
  ],
  [
    'Follow a discussion on an unfamiliar topic',
    'Organise your thoughts quickly',
    'Respond without translating first',
    'Ask questions to learn more',
    'Join a conversation without a prepared script',
  ],
  [
    'Understand people in different situations',
    'Start and maintain conversations',
    'Tell stories and explain ideas',
    'Solve problems and discuss options',
    'Get through a full day using English',
  ],
]
